### ISSUE TITLE
Build only works when other SublimeREPL files not present

### ISSUE THREAD

**Issue by snadi** [gsdlab/ClaferToolsST#2]
Operating System: OS X Yosemite Version 10.10.2

Following the installation instructions, <CTRL>+b only works if the only folder under SublimREPL is 'config' -- i.e., if you do a replace and not a merge when copying SublimeREPL from 'Clafer Tools'. It will still work if you also include the other language folders under 'config' (i.e., Perl etc.). However, the other files in the original SublimeREPL folder seem to cause <CTRL>+b to stop working.

Also, all instance generation commands do not work for me in either case (e.g., <CTRL>+i, g, a). I tried both <Ctrl> and <Cmd> on mac. Pressing <Cmd>+i first triggers the search while <Ctrl>+i does nothing.

**Comment by ross2jd** [comment]
Instance generation commands on the mac OS use "control" + "i" + "g" + (a or c). This should probably more explicit in the documentation.

**Comment by snadi** [comment]
Thanks, this sequence does show the chaining, but the instance generator is still not triggered. I'll check if it is something wrong with my installation. 

What about the first part: The fact that I had to completely replace the SublimeREPL folder? Wouldn't that affect other functionalities ?

**Comment by ross2jd** [comment]
It should not. What it will do when you paste is it will merge the two folders structures together (basically only affecting the old Clafer files).

**Comment by mantkiew** [comment]
I don't understand. The subfolders in SublimeRepl should not be removed, that's for sure. Just reinstall it to get them back. Copy the ClaferIG folder into config or do a merge. Do not do replace. If you remove SublimeREPL's folders then, of course, the shortcuts will stop working. `<ctrl>+i+g+a` should always work because it's an executable being looked up in `Clafer-Bin` (no PATH issues).

Now, `<ctrl>+b` is a build system and has nothing to do with SublimeREPL, which is only for interactive, terminal-like, interactions. The behavior of `<ctrl>+b` is defined in `clafer.sublime-build` in the `Clafer Tools` folder. Sometimes, however, the file autodetection fails (Sublime should pick Clafer as a build system for a .cfr file). Go to `Tools->Build System`. `Automatic` should do the selection. Otherwise, you can select `clafer` from the list manually.

**Comment by snadi** [comment]
Thanks, everything works now. I just put back the other SublimeREPL folders and even though it was not working the first time, it is now. Thanks!
